### ISSUE TITLE
CDP Testnet Meta Issue

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/kava#327]
Items to test/verify before release

- [x] Param Change Proposals
  - [x]  Adding market to pricefeed
  - [x]  Adding collateral to cdp
  - [x]  Multiple key attributes changed by one proposal
  - [x]  Increasing debt limit for a collateral type
  - [x]  Add oracles to existing market
  - [x]  Update collateral auction bid duration
  - [x]  Update collateral auction max duration

- [x] Auction Testing
  - [x]  Test collateral auction forward behavior
  - [x]  Test collateral auction reverse behavior
  - [x]  Creation of debt, surplus tokens appropriately
  - [x]  Test Debt Auction behavior - bug: https://github.com/Kava-Labs/kava/pull/333
  - [x]  Test Surplus Auction behavior - bug: https://github.com/Kava-Labs/kava/pull/333

- [x]  PR for Kava tools
- [ ]  PR for pricefeed spec

- [ ] REST Server Methods
  - [x]  Test any remaining REST server methods 
  - [ ]  Add Swagger doc comments for REST server methods

**Comment by denalimarsh** [comment]
**1. [INFO]** Proposals overwrite all existing content in the param key specified. So adding market “bnb-usd” to the pricefeed oracle requires that the proposal includes existing markets “xrp-usd” and “btc-usd” along with the new market, otherwise the existing markets will be removed when the proposal passes. This means that when an oracle is added to a market, _technically_ an entirely new market that contains an oracle replaces an existing market with the same name.

**2. [BUG]**  When the debt limit is changed - in this case from `10,000,000usdx` to `10,000usdx` - the CDP module's params show the correct change. However, attempting to create a CDP with the new debt limit fails because the module continues to enforce the old minimum of `10,000,000usdx`:
<img width="1063" alt="Screen Shot 2020-01-22 at 7 10 58 PM" src="https://user-images.githubusercontent.com/15370712/72953854-5704df00-3d4b-11ea-9a9f-a89fcec03aa4.png">

 
**3. [FATAL]** Proposals update params, but don't execute initialization methods in `InitGenesis()` that the CDP module relies upon. When a new collateral type is added to the CDP module, it is correctly shown in the params. But attempting to open any CDP _with any collateral type_ will give error:
`E[2020-01-22|19:31:14.235] CONSENSUS FAILURE!!!                         module=consensus err="total principal of usdx for bnb collateral not set in genesis"`. Attempting to restart the chain gives the same error.

The problem is that `SetTotalPrincipal()` is never called for the new collateral type, it's only called in `InitGenesis()`. According to the [spec](https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/spec/04_events.md), the governance module emits event `active_proposal` that contains `proposal_id` and `proposal_result`. 'They are emitted at EndBlock, they cannot be queried but can be subscribed' - bez.

**A potential solution:**
a. Subscribing to the gov's `active_proposal` event and check in BeginBlocker
b. If `proposal_result` == 3, query gov module for the proposal's contents
c. If `content.changes[...].key == CollateralParams`, parse the fields we need from `content.changes[i].value` and call the required collateral setup functions

**Comment by rhuairahrighairidh** [comment]
For **3.**, it might be enough to modify `GetTotalPrinciple` to return 0 when none is found in the store.

**Comment by rhuairahrighairidh** [comment]
For 1, it's probably worth us investigating at some point using a custom gov proposal type to update collateral and debt params.

**Comment by karzak** [comment]
For 2, USDX is in 10^-6 units. So the debt floor of 10,000,000 is 10 USDX, which is the expected behavior. I would say that setting the debt limit below debt floor should be rejected by a validation process in `param-change` proposals.  

It looks like this is already implemented upstream in the `cosmos-sdk`: https://github.com/cosmos/cosmos-sdk/issues/3473

**Comment by karzak** [comment]
Submitted a fix for 3 via #329

**Comment by denalimarsh** [comment]
> For 1, it's probably worth us investigating at some point using a custom gov proposal type to update collateral and debt params.

Even with the validation from https://github.com/cosmos/cosmos-sdk/issues/3473, I think adding custom gov proposals for common/expected proposals would be beneficial.

**Comment by rhuairahrighairidh** [comment]
debt and surplus auction tested

**Comment by denalimarsh** [comment]
What is the status of this issue? Can it be closed?

**Comment by karzak** [comment]
Closing, will open remaining issues as separate topics.
